# Generated by Django 4.2.5 on 2023-09-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False, 'ordering': ['updated', 'created']},
        ),
    ]
