# Generated by Django 4.2.5 on 2023-09-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
